#!/usr/bin/env python3
r"""smoke_test - prove the skill's whole toolchain actually works on this machine.

Run this after installing, after a Python or LibreOffice upgrade, and any time a
document operation starts behaving strangely. It exercises the real path
(build -> inspect -> edit -> validate -> render) for docx, xlsx, and pptx, and
fails loudly on the first broken link rather than leaving you to guess.

    ~/.dsh/office-docs/venv/bin/python scripts/smoke_test.py
    ~/.dsh/office-docs/venv/bin/python scripts/smoke_test.py --keep   # keep artifacts

Exit code 0 means every check passed. Each check prints PASS/FAIL/SKIP, and the
summary names the ones that failed.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
OFFICE = SCRIPT_DIR / "office.py"
EDIT = SCRIPT_DIR / "docx_edit.py"

RESULTS: list[tuple[str, str, str]] = []


def record(name: str, ok: bool, detail: str = "", skipped: bool = False) -> None:
    status = "SKIP" if skipped else ("PASS" if ok else "FAIL")
    RESULTS.append((name, status, detail))
    line = f"{status}  {name}"
    if detail:
        line += f"  -  {detail.splitlines()[0][:150]}"
    print(line, flush=True)


def run(args: list[str]) -> subprocess.CompletedProcess:
    return subprocess.run([sys.executable, *args], capture_output=True, text=True)


def check(name: str, args: list[str], expect_rc: int = 0, expect_in: str | None = None) -> subprocess.CompletedProcess:
    proc = run(args)
    output = (proc.stdout or "") + (proc.stderr or "")
    ok = proc.returncode == expect_rc and (expect_in is None or expect_in in output)
    record(name, ok, "" if ok else f"rc={proc.returncode} expected={expect_rc}\n{output}")
    return proc


SAMPLE_MD = r"""# Smoke Test Document

A paragraph with **bold**, *italic*, and `code` plus an equation $a^2 + b^2 = c^2$.

## Lists

- first bullet
- second bullet
  - nested bullet

1. first number
2. second number

| Metric | Value |
|:---|---:|
| Alpha | 1 |
| Beta | 2 |

> A block quote.

\pagebreak

## After the break

```python
print("code block")
```

Note: a callout paragraph.
"""


def make_samples(tmp: Path) -> None:
    md = tmp / "sample.md"
    md.write_text(SAMPLE_MD, encoding="utf-8")

    import openpyxl
    from openpyxl.styles import Alignment, Font, PatternFill
    from openpyxl.utils import get_column_letter

    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Revenue"
    headers = ["Region", "Q1", "Q2", "Total"]
    for col, header in enumerate(headers, start=1):
        cell = ws.cell(row=1, column=col, value=header)
        cell.font = Font(name="Arial", bold=True, color="FFFFFF")
        cell.fill = PatternFill("solid", fgColor="1F3A5F")
        cell.alignment = Alignment(horizontal="center")
    rows = [("North America", 120, 145), ("EMEA", 90, 88), ("APAC", 70, 95)]
    for idx, (region, q1, q2) in enumerate(rows, start=2):
        ws.cell(row=idx, column=1, value=region).font = Font(name="Arial")
        ws.cell(row=idx, column=2, value=q1).font = Font(name="Arial")
        ws.cell(row=idx, column=3, value=q2).font = Font(name="Arial")
        ws.cell(row=idx, column=4, value=f"=B{idx}+C{idx}").font = Font(name="Arial")
    ws.cell(row=len(rows) + 2, column=1, value="Total").font = Font(name="Arial", bold=True)
    ws.cell(row=len(rows) + 2, column=4, value=f"=SUM(D2:D{len(rows) + 1})").font = Font(name="Arial", bold=True)
    ws.column_dimensions["A"].width = 20
    for col in "BCD":
        ws.column_dimensions[col].width = 10
    ws.freeze_panes = "A2"
    wb.save(tmp / "sample.xlsx")

    from pptx import Presentation
    from pptx.util import Inches, Pt

    prs = Presentation()
    title_slide = prs.slides.add_slide(prs.slide_layouts[0])
    title_slide.shapes.title.text = "Smoke Test Deck"
    title_slide.placeholders[1].text = "Generated by the office-docs skill"
    content = prs.slides.add_slide(prs.slide_layouts[1])
    content.shapes.title.text = "Findings"
    body = content.placeholders[1].text_frame
    body.text = "First finding"
    para = body.add_paragraph()
    para.text = "Second finding"
    para.font.size = Pt(18)
    table_slide = prs.slides.add_slide(prs.slide_layouts[5])
    table_slide.shapes.title.text = "Numbers"
    table = table_slide.shapes.add_table(2, 2, Inches(1), Inches(2), Inches(6), Inches(1.2)).table
    for r, row in enumerate([("Region", "Total"), ("APAC", "165")]):
        for c, value in enumerate(row):
            table.cell(r, c).text = value
    prs.save(tmp / "sample.pptx")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--keep", action="store_true", help="keep generated artifacts for inspection")
    ap.add_argument("--dir", help="work in this directory instead of a temporary one")
    args = ap.parse_args()

    tmp = Path(args.dir) if args.dir else Path(tempfile.mkdtemp(prefix="office-docs-smoke-"))
    tmp.mkdir(parents=True, exist_ok=True)
    print(f"Working in {tmp}\n")

    # 0. environment
    try:
        import docx  # noqa: F401
        import openpyxl  # noqa: F401
        import pptx  # noqa: F401

        record("python document libraries import", True)
    except Exception as exc:  # noqa: BLE001
        record("python document libraries import", False, str(exc))
        print("\nRun scripts/bootstrap.py first.", file=sys.stderr)
        return 1
    has_soffice = shutil.which("soffice") is not None or shutil.which("libreoffice") is not None
    record("LibreOffice present", has_soffice, "" if has_soffice else "soffice not on PATH", skipped=not has_soffice)
    has_pdftoppm = shutil.which("pdftoppm") is not None
    record("poppler (pdftoppm) present", has_pdftoppm, "" if has_pdftoppm else "pdftoppm not on PATH", skipped=not has_pdftoppm)

    try:
        make_samples(tmp)
        record("generate sample docx/xlsx/pptx", True)
    except Exception as exc:  # noqa: BLE001
        record("generate sample docx/xlsx/pptx", False, str(exc))
        return summarize(tmp, args.keep)

    # 1. build a docx from Markdown
    check(
        "docx: markdown -> docx",
        [str(OFFICE), "new", str(tmp / "sample.md"), "--out", str(tmp / "built.docx"), "--title", "Smoke Test", "--toc", "--page-numbers"],
        expect_in="OK",
    )

    # 2. look at it
    check("docx: info reports the package", [str(OFFICE), "info", str(tmp / "built.docx")], expect_in="OOXML package")
    check("docx: dump extracts text", [str(OFFICE), "dump", str(tmp / "built.docx")], expect_in="Smoke Test Document")

    # 3. structural validation
    check("docx: validate clean file", [str(OFFICE), "validate", str(tmp / "built.docx")], expect_in="OK:")

    # 4. tracked editing
    shutil.copy(tmp / "built.docx", str(tmp / "edit.docx"))
    check(
        "docx: tracked find-replace",
        [str(EDIT), "find-replace", str(tmp / "edit.docx"), str(tmp / "edit.docx"), "--old", "bold", "--new", "BOLD", "--author", "Smoke Tester"],
        expect_in="replaced 1",
    )
    check(
        "docx: tracked edit validates against original",
        [str(OFFICE), "validate", str(tmp / "edit.docx"), "--original", str(tmp / "built.docx"), "--author", "Smoke Tester"],
        expect_in="OK:",
    )
    check("docx: merge-runs is a no-op-safe rewrite", [str(EDIT), "merge-runs", str(tmp / "edit.docx"), "-o", str(tmp / "merged.docx")], expect_in="merged")
    check(
        "docx: comment anchors to text",
        [str(EDIT), "comment", str(tmp / "merged.docx"), "-o", str(tmp / "commented.docx"), "--text", "A reviewer note", "--anchor", "block quote", "--author", "Smoke Tester"],
        expect_in="anchored",
    )
    check(
        "docx: validate catches an untracked edit",
        [str(EDIT), "find-replace", str(tmp / "built.docx"), str(tmp / "sneaky.docx"), "--old", "bold", "--new", "SNEAKY", "--no-track"],
        expect_in="replaced 1",
    )
    proc = run([str(OFFICE), "validate", str(tmp / "sneaky.docx"), "--original", str(tmp / "built.docx"), "--author", "Smoke Tester"])
    detected = proc.returncode == 1 and "nothing is wrapped in a tracked revision" in (proc.stdout + proc.stderr)
    record(
        "docx: validator rejects untracked change",
        detected,
        "" if detected else f"validator did not detect the untracked edit (rc={proc.returncode})",
    )
    check("docx: accept revisions", [str(EDIT), "accept", str(tmp / "edit.docx"), str(tmp / "accepted.docx")], expect_in="accepted")
    check("docx: accepted file still validates", [str(OFFICE), "validate", str(tmp / "accepted.docx")], expect_in="OK:")

    # 5. xlsx
    check("xlsx: info", [str(OFFICE), "info", str(tmp / "sample.xlsx")], expect_in="OOXML package")
    check("xlsx: dump shows formulas and values", [str(OFFICE), "dump", str(tmp / "sample.xlsx")], expect_in="Sheet: Revenue")
    check("xlsx: validate (formula errors)", [str(OFFICE), "validate", str(tmp / "sample.xlsx")], expect_in="OK:")

    # 6. pptx
    check("pptx: info", [str(OFFICE), "info", str(tmp / "sample.pptx")], expect_in="OOXML package")
    check("pptx: dump walks slides", [str(OFFICE), "dump", str(tmp / "sample.pptx")], expect_in="Slide 2")
    check("pptx: validate", [str(OFFICE), "validate", str(tmp / "sample.pptx")], expect_in="OK:")

    # 7. conversion + rendering
    if has_soffice:
        check("convert: docx -> pdf", [str(OFFICE), "convert", str(tmp / "built.docx"), "--to", "pdf"], expect_in="OK")
        check("convert: xlsx -> csv", [str(OFFICE), "convert", str(tmp / "sample.xlsx"), "--to", "csv"], expect_in="OK")
        check("convert: pptx -> pdf", [str(OFFICE), "convert", str(tmp / "sample.pptx"), "--to", "pdf"], expect_in="OK")
    if has_soffice and has_pdftoppm:
        check(
            "render: pages to images",
            [str(OFFICE), "render", str(tmp / "built.docx"), "--outdir", str(tmp), "--prefix", str(tmp / "page"), "--dpi", "80"],
            expect_in="page image",
        )
    check(
        "negative: missing file is a clean error",
        [str(OFFICE), "info", str(tmp / "does-not-exist.docx")],
        expect_rc=1,
        expect_in="no such file",
    )

    return summarize(tmp, args.keep)


def summarize(tmp: Path, keep: bool) -> int:
    failed = [name for name, status, _ in RESULTS if status == "FAIL"]
    skipped = [name for name, status, _ in RESULTS if status == "SKIP"]
    print(f"\n{len(RESULTS) - len(failed) - len(skipped)} passed, {len(failed)} failed, {len(skipped)} skipped")
    for name, status, detail in RESULTS:
        if status == "FAIL":
            print(f"\nFAILED: {name}\n{detail}")
    if keep:
        print(f"\nArtifacts kept in {tmp}")
    else:
        shutil.rmtree(tmp, ignore_errors=True)
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
